question_data = [
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "The common software-programming acronym 'I18N' comes from the term 'Interlocalization'.",
            "correct_answer": "False",
            "incorrect_answers": ["True"]
            },
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "To bypass US Munitions Export Laws, "
                     "the creator of the PGP published all the source code in book form. ",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "MacOS is based on Linux.", "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The open source program Redis is a relational database server.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "AMD created the first consumer 64-bit processor.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The first dual-core CPU was the Intel Pentium D.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {
            "category": "Science: Computers",
            "type": "boolean",
            "difficulty": "medium",
            "question": "Android versions are named in alphabetical order.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        }
]
